const String baseUrl = "http://choice-app-prod-env.eba-wqrm9be2.eu-west-3.elasticbeanstalk.com";//production url


const String loginApiUrl = "$baseUrl/api/producer/auth/login";
const String userLoginApiUrl = "$baseUrl/api/app/auth/login";
const String signUpApiUrl = "$baseUrl/api/producer/auth/register";
const String userSignUpApiUrl = "$baseUrl/api/app/auth/register";
const String verifySignupOtpApiUrl = "$baseUrl/api/producer/auth/verifyOtp";
const String verifyUserSignupOtpApiUrl = "$baseUrl/api/app/auth/verifyOtp";
const String resendSignupOtpApiUrl = "$baseUrl/api/producer/auth/resendSignUpOtp";
const String resendUserSignupOtpApiUrl = "$baseUrl/api/app/auth/resendSignUpOtp";
const String verifyFgOtpApiUrl = "$baseUrl/api/producer/auth/verifyForgotPasswordOtp";
const String verifyUserFgOtpApiUrl = "$baseUrl/api/app/auth/verifyForgotPasswordOtp";
const String resendFgOtpApiUrl = "$baseUrl/api/producer/auth/resendForgotPasswordOtp";
const String resendUserFgOtpApiUrl = "$baseUrl/api/app/auth/resendForgotPasswordOtp";
const String forgotPasswordApiUrl = "$baseUrl/api/producer/auth/forgotPassword";
const String forgotUserPasswordApiUrl = "$baseUrl/api/app/auth/forgotPassword";
const String resetPasswordApiUrl = "$baseUrl/api/producer/auth/resetPassword";
const String resetUserPasswordApiUrl = "$baseUrl/api/app/auth/resetPassword";
const String submitDocsApiUrl = "$baseUrl/api/producer/auth/submitDocuments";
const String preSignedFileUploadApiUrl = "$baseUrl/api/producer/auth/getPreSignedUrl";
const String createUserPostApiUrl = "$baseUrl/api/producer/post/createUserPost";
const String createEventPostApiUrl = "$baseUrl/api/producer/event/createEvent";
const String getAllEventsApiUrl = "$baseUrl/api/producer/event/getAllEvents";
const String updateProfileApiUrl = "$baseUrl/api/producer/profile/updateProfile";
const String setOperationalHoursApiUrl = "$baseUrl/api/producer/profile/setOperationalHours";
const String getCuisineTypesApiUrl = "$baseUrl/api/producer/profile/getCuisineTypes";
const String setCuisineTypeApiUrl = "$baseUrl/api/producer/profile/setCuisineType";
const String setGalleryImagesApiUrl = "$baseUrl/api/producer/profile/setGalleryImages";
const String addMenuCategoryApiUrl = "$baseUrl/api/producer/profile/addMenuCategory";
const String addMenuDishApiUrl = "$baseUrl/api/producer/profile/addMenuDish";
const String getMenuCategoriesApiUrl = "$baseUrl/api/producer/profile/getMenuCategories";
const String userProfileApiUrl = "$baseUrl/api/app/profile/getProfile";
const String userPostsApiUrl = "$baseUrl/api/producer/post/getMyPosts";